### ISSUE TITLE
Connect to Redis Server with Password

### ISSUE THREAD

**Issue by Budaoshi** [anandtrex/redis-browser#2]
Our redis server is authorized with user's password. How do we impls this?

**Comment by anandtrex** [comment]
@Budaoshi You can use a redis url of the format `redis://user:password@host:port` or `redis://:password@host:port` for just using a password.

**Comment by Budaoshi** [comment]
> @Budaoshi You can use a redis url of the format `redis://user:password@host:port` or `redis://:password@host:port` for using only a password.
Thanks @anandtrex. `redis://:password@host:port` do work!!!
